# Site settings
title: Guida TV, la migliore guida TV italiana
email:
description: Guida TV, la migliore guida TV italiana su misura per te

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://jekynewage.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-90693092-1"
addthis_id: ra-5883c442259b8057
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  #- title: twitter
  #  url: https://twitter.com/mobinow
  - title: facebook
    url: https://www.facebook.com/guidatvonline
  #- title: google-plus
  #  url: https://plus.google.com/+mobinow
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
